  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: notification-service
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: notification-service


    template:
      metadata:
        labels:
          app: notification-service

      spec:
        containers:
        - name: eureka-server
          image: microservicecon.azurecr.io/notification-service

          ports:
          - containerPort: 8080
