  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: config-server
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: config-server
    template:
      metadata:
        labels:
          app: config-server
      spec:
        containers:
        - name: config-server
          image: microservicecon.azurecr.io/config-server
          ports:
          - containerPort: 8080
