  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: eureka-server
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: eureka-server

    template:
      metadata:
        labels:
          app: eureka-server
      spec:
        containers:
        - name: eureka-server
          image: microservicecon.azurecr.io/eureka-server
          ports:
          - containerPort: 8080
