  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: auth-service
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: auth-service
    template:
      metadata:
        labels:
          app: auth-service
      spec:
        containers:
        - name: auth-service
          image: microservicecon.azurecr.io/auth-service
          ports:
          - containerPort: 8080
