  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: user-service

  spec:
    replicas: 3
    selector:
      matchLabels:
        app: user-service

    template:
      metadata:
        labels:
          app: user-service
      spec:
        containers:
        - name: eureka-server
          image: microservicecon.azurecr.io/user-service
          ports:
          - containerPort: 8080
