  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: job-service
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: job-service

    template:
      metadata:
        labels:
          app: job-service
      spec:
        containers:
        - name: job-service
          image: microservicecon.azurecr.io/job-service
          ports:
          - containerPort: 8080
