name: CI/CD for Microservices

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: microservicecon.azurecr.io  # Azure ACR login server (e.g., myacr.azurecr.io)
          username: microservicecon
          password: 3qZV8ZC53McCVQhwWMiVNT6sNFXymDYNVyV52L+lZ0+ACRAQ2gIl # ACR password

      # 4. Build Docker Image for auth-service
      - name: Build Docker Image for auth-service
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.ACR_LOGIN_SERVER }}/auth-service:latest ./auth-service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/auth-service:latest

      # 5. Build Docker Image for config-server
      - name: Build Docker Image for config-server
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.ACR_LOGIN_SERVER }}/config-server:latest ./config-server
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/config-server:latest

      # 6. Build Docker Image for eureka-server
      - name: Build Docker Image for eureka-server
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.ACR_LOGIN_SERVER }}/eureka-server:latest ./eureka-server
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/eureka-server:latest

      # 7. Build Docker Image for file-storage
      - name: Build Docker Image for file-storage
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.ACR_LOGIN_SERVER }}/file-storage:latest ./file-storage
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/file-storage:latest

      # 8. Build Docker Image for gateway
      - name: Build Docker Image for gateway
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.ACR_LOGIN_SERVER }}/gateway:latest ./gateway
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/gateway:latest

      # 9. Build Docker Image for job-service
      - name: Build Docker Image for job-service
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.ACR_LOGIN_SERVER }}/job-service:latest ./job-service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/job-service:latest

      # 10. Build Docker Image for notification-service
      - name: Build Docker Image for notification-service
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.ACR_LOGIN_SERVER }}/notification-service:latest ./notification-service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/notification-service:latest

      # 11. Build Docker Image for user-service
      - name: Build Docker Image for user-service
        run: |
          docker buildx build --platform linux/amd64 --tag ${{ secrets.ACR_LOGIN_SERVER }}/user-service:latest ./user-service
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/user-service:latest
